name: Generate Vanitydoc Site

on:
  push:
    branches:
      - main
    paths:
      - config.json
      - '.github/workflows/vanitydoc.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install vanitydoc
        run: go install code.pfad.fr/vanitydoc@latest

      - name: Generate documentation site
        run: vanitydoc config.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
